### PR TITLE
Feature/implement auth

### PR DESCRIPTION
**Pull request by M1-Elmasry**

### CODE REVIEW

**Comment by Davenchy** [comment]
While testing, the following issues occurred:
- `POST /auth/login`: The controller generates and returns a token even if the password is incorrect.
  - Probably the problem at `authControllers.ts:62` the method `bcrypt.compare` returns `Promise<boolean>`, So it will be always true, even if the password is incorrect.

**Comment by Davenchy** [comment]
While testing `GET /auth/me` the following **Authorization Header** passes while it should not:
`hello eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmJiNGY4Y2M4ZWM0ZWJjMGQ3OWMzZjUiLCJpYXQiOjE3MjM2NDQwMTQsImV4cCI6MTcyNDI0ODgxNH0.95pcnpNh-ZP0OmAOUfsfsEQD-3oEr0J7CPVY1slkdgw`

I suggest validating the authentication method in the `verifyToken` middleware.

**Comment by M1-Elmasry** [comment]
got it, working on it

**Comment by Davenchy** [comment]
``

> got it, working on it

I have already done, and going to push it.

**Comment by M1-Elmasry** [comment]
I've implemented the fixes locally, but if you fix it too and have any additional improvements feel free to add it and make another PR

**Pull request merged**
